import ee
import pandas as pd
import geopandas as gpd
import time
from config import BUFFER_RADIUS_M, GEE_SCALE_M, CHUNK_SIZE

def init_gee():
    try:
        ee.Initialize()
        print("✅ Google Earth Engine successfully initialized with existing credentials.")
    except Exception:
        print("🔑 Credentials not found or expired. Requesting authentication...")
        ee.Authenticate()
        ee.Initialize()
        print("✅ Google Earth Engine successfully authenticated and initialized.")


def build_esg_composite():
    viirs = ee.ImageCollection('NOAA/VIIRS/DNB/ANNUAL_V22').filterDate('2022-01-01', '2023-01-01').select('average').median().rename('night_radiance')
    era5 = ee.ImageCollection('ECMWF/ERA5_LAND/MONTHLY_AGGR').filterDate('2023-01-01', '2024-01-01').select('surface_solar_radiation_downwards_sum').mean().rename('solar_radiation')
    worldpop = ee.ImageCollection('WorldPop/GP/100m/pop').filterDate('2020-01-01', '2021-01-01').select('population').mean().rename('population')
    nasadem = ee.Image('NASA/NASADEM_HGT/001')
    elevation = nasadem.select('elevation').rename('elevation')
    slope = ee.Terrain.slope(elevation).rename('slope')
    rainfall = ee.ImageCollection('NASA/GPM_L3/IMERG_V07').filterDate('2023-01-01', '2024-01-01').select('precipitation').mean().rename('rainfall')
    
    return ee.Image.cat([viirs, era5, worldpop, elevation, slope, rainfall])

def extract_gee_data(df_sites):
    init_gee()
    composite = build_esg_composite()
    
    all_records = []
    total_sites = len(df_sites)
    
    print(f"⏳ Extracting GEE data in chunks of {CHUNK_SIZE}...")
    
    for i in range(0, total_sites, CHUNK_SIZE):
        chunk = df_sites.iloc[i:i + CHUNK_SIZE]
        
        # Casting to prevent JSON serialization anomalies from Pandas/NumPy types.
        features = [
            ee.Feature(
                ee.Geometry.Point(float(row['longitude']), float(row['latitude'])), 
                {'site_id': int(row['site_id'])}
            )
            for _, row in chunk.iterrows()
        ]
        
        fc = ee.FeatureCollection(features).map(lambda f: f.buffer(BUFFER_RADIUS_M))

        # to be removed 
        # SAFEGUARD: Filter out any geometries that fall completely outside 
        # the composite raster boundaries to prevent out-of-bounds computation errors.
        #runnable_fc = fc.filterBounds(composite.geometry()) 

        combined_reducer = ee.Reducer.mean().combine(reducer2=ee.Reducer.sum(), sharedInputs=True)
        
        # Added crs='EPSG:4326' to mirror the working legacy function
        reduced = composite.reduceRegions(
            collection=fc,
            reducer=combined_reducer,
            scale=GEE_SCALE_M,  # 500m 
            crs='EPSG:4326',
            tileScale=4
        )
        
        # Wrapped .getInfo() in a try-except block for safe error handling
        try:
            data = reduced.getInfo()
            for feature in data.get('features', []):
                props = feature.get('properties', {})
                all_records.append(props)
        except Exception as e:
            print(f"❌ GEE Server-Side Error Caught on chunk starting at index {i}: {e}")
            raise e
            
        print(f"    Processed {min(i + CHUNK_SIZE, total_sites)} / {total_sites} sites...")
        time.sleep(1) # resting time
        
    df_env = pd.DataFrame(all_records)
    return df_env

def clean_and_merge(df_ookla, df_env):
    # Check if df_env is empty to prevent errors if a chunk failed silently
    if df_env.empty:
        raise ValueError("❌ df_env is completely empty. No features were returned from GEE.")

    # Standardize 'site_id' columns to string type to resolve the merge conflict
    df_ookla['site_id'] = df_ookla['site_id'].astype(str)
    df_env['site_id'] = df_env['site_id'].astype(float).astype(int).astype(str)

    master_df = pd.merge(df_ookla, df_env, on='site_id', how='inner')


    # Explicitly rename using the appended suffix mapping generated by GEE's combined reducer
    master_df = master_df.rename(columns={
        'elevation_mean': 'elevation_m',
        'slope_mean': 'slope_degrees',
        'rainfall_mean': 'rainfall_mm_hr',
        'night_radiance_mean': 'night_radiance_nw_cm2_sr', 
        'population_sum': 'population_total',
        'solar_radiation_mean': 'solar_radiation_raw'
    })
    
    if 'solar_radiation_raw' in master_df.columns:
        master_df['solar_radiation_mj'] = master_df['solar_radiation_raw'] / 1000000.0
        
    columns_to_drop = [
        'elevation_sum', 'population_mean', 'night_radiance_sum', 
        'rainfall_sum', 'slope_sum', 'solar_radiation_sum', 'solar_radiation_raw'
    ]
    master_df = master_df.drop(columns=columns_to_drop, errors='ignore')
    
    # Fill Coastal Zeros from ERA5
    master_df['solar_radiation_mj'] = master_df['solar_radiation_mj'].fillna(0)

    # Convert back to a GeoDataFrame using the existing coordinates
    master_df = gpd.GeoDataFrame(
        master_df,
        geometry=gpd.points_from_xy(master_df['longitude'], master_df['latitude']),
        crs='EPSG:4326'
    )
    return master_df